---

- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 86400
    
- name: Aptitude must be present
  apt: 
    name: aptitude

- name: iptables-persistent must be present
  apt: 
    name: iptables-persistent

- name: Copy firewall script to servers
  template:
    src: templates/firewall.j2
    dest: /home/{{ ansible_user }}/firewall.sh
  register: firewallrules

- name: Set Execute Perms for Firewall Script
  file:
    path: /home/{{ ansible_user }}/firewall.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: run firewall script
  become: yes
  shell: /home/{{ ansible_user }}/firewall.sh
  when: firewallrules.changed

- name: save IPTables
  become: yes
  shell: service netfilter-persistent save
  when: firewallrules.changed