---

#Define hosts this playbook will operate on
- hosts: all
  become: yes


#Tasks to execute
  tasks:
  - name: Update Apt Cache
    apt: 
      update_cache: yes
      cache_valid_time: 86400

  - name: Upgrade packages
    apt: 
      upgrade: dist