---

- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 86400

- name: Make sure Apache is installed
  apt: 
    name: apache2

- name: Make sure Apache is started
  service:
    name: apache2
    state: started